sonar.organization=open-innovation-team
sonar.projectKey=open-innovation-team

# Monorepo : on scanne les apps, on exclut le reste
sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.expo/**,**/coverage/**,**/*.test.ts,**/*.spec.ts

# Si tu génères de la couverture (lcov) :
# sonar.javascript.lcov.reportPaths=apps/backend/api/coverage/lcov.info,apps/web/coverage/lcov.info

31b359ecf8d1fa548ec73e5553b837cc3840aa65
