// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
// Le .env unique du monorepo se trouve a la racine.
config({ path: '../../../.env' });
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
  },
});
